#!/bin/bash

export EPICS_APP=`dirname ${BASH_SOURCE:-$0}`
export EPICS_APP_ADL_DIR=${EPICS_APP}/oh26App/op/adl
export DEFAULT_UI_FILE=${1:-${DEFAULT_UI_FILE:-oh26.adl}}
export UI_FILE_MACROS=${2:-"P=oh26:"}

source ${EPICS_APP}/setup_epics_common medm

if [ -z "${MEDM_EXEC_LIST}" ]
then
    export MEDM_EXEC_LIST='Probe;probe &P &'
fi

#export EPICS_CA_ADDR_LIST="164.54.53.126"

# This should agree with the environment variable set by the ioc
# see 'putenv "EPICS_CA_MAX_ARRAY_BYTES=64008"' in iocBoot/ioc<target>/st.cmd
export EPICS_CA_MAX_ARRAY_BYTES=64008

export START_PUTRECORDER=${EPICS_APP}/start_putrecorder
export MACROS_PY=${EPICS_APP_ADL_DIR}/../python/macros.py
export EDITOR=nedit

# We have multiple network interfaces so we need
# to do this to avoid "Identical Process Variable names on Multiple Servers" errors
export EPICS_CA_AUTO_ADDR_LIST=NO
export EPICS_CA_ADDR_LIST="127.0.0.1"

medm -macro ${UI_FILE_MACROS} -x ${DEFAULT_UI_FILE} &
