#!/bin/bash
# A script to start the urRobot screens with either MEDM or caQtDM.

# cd to this script's directory
script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
cd "$script_dir" || exit

# Define paths to display manager binaries
# CAQTDM=/APSshare/bin/caQtDM
MEDM=medm

# Display manager to use
# DM="${1:-caqtdm}"
DM="medm"

SUPPORT="/home/nmarks/open-house/support"

# Path to the URROBOT support module
URROBOT_PATH="${SUPPORT}/urRobot-master"

# IOC prefix
PREFIX="oh26:UR:"

# Some screens are used from the calc module
CALC=${SUPPORT}/calc-master
# If using Robotiq wrist camera, need areaDetector
AREA_DETECTOR="${SUPPORT}/areaDetector-master"

####################################################

if [[ $DM == "caqtdm" ]]; then
    export UI_DIR=${URROBOT_PATH}/urRobotApp/op/ui
    export CAQTDM_DISPLAY_PATH=$CAQTDM_DISPLAY_PATH:${UI_DIR}
    export CAQTDM_DISPLAY_PATH=$CAQTDM_DISPLAY_PATH:${UI_DIR}/autoconvert
    export CAQTDM_DISPLAY_PATH=$CAQTDM_DISPLAY_PATH:${CALC}/calcApp/op/ui
    export CAQTDM_DISPLAY_PATH=$CAQTDM_DISPLAY_PATH:${CALC}/calcApp/op/ui/autoconvert/
    export CAQTDM_DISPLAY_PATH=$CAQTDM_DISPLAY_PATH:${AREA_DETECTOR}/ADCore/ADApp/op/ui/autoconvert/
    ${CAQTDM} -style plastique -noMsg -macro "P=${PREFIX}" "urRobot.ui" &
elif [[ $DM == "medm" ]]; then
    export ADL_DIR=${URROBOT_PATH}/urRobotApp/op/adl
    export EPICS_DISPLAY_PATH=${ADL_DIR}
    export EPICS_DISPLAY_PATH=${ADL_DIR}:${CALC}/calcApp/op/adl
    export EPICS_DISPLAY_PATH=$EPICS_DISPLAY_PATH:${AREA_DETECTOR}/ADCore/ADApp/op/adl/
    ${MEDM} -macro "P=${PREFIX}" -x "urRobot.adl" &
else
    echo "Display manager must be either medm or caqtdm"
fi
