#!/bin/bash

export EPICS_APP=`dirname ${BASH_SOURCE:-$0}`
export EPICS_APP_ADL_DIR=${EPICS_APP}/oh26App/op/adl
export DEFAULT_UI_FILE=${1:-${DEFAULT_UI_FILE:-oh26.adl}}
export UI_FILE_MACROS=${2:-"P=oh26:"}

source ${EPICS_APP}/setup_epics_common medm

if [ -z "${MEDM_EXEC_LIST}" ]
then
    export MEDM_EXEC_LIST='Probe;probe &P &'
fi

export EPICS_CA_MAX_ARRAY_BYTES=64010

# We have multiple network interfaces so we need
# to do this to avoid "Identical Process Variable names on Multiple Servers" errors
export EPICS_CA_AUTO_ADDR_LIST=NO
export EPICS_CA_ADDR_LIST="127.0.0.1"

medm -macro ${UI_FILE_MACROS} -x ${DEFAULT_UI_FILE} &
